sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "6"
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
script:
  - npm run -s lint
  - npm run -s cover
  - npm run -s check-coverage
  - npm run -s build
after_success:
  - npm run -s report-coverage
  - npm run -s semantic-release
branches:
  only:
    - master
